name: lint-and-typecheck

on:
  pull_request:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==25.1.0 mypy==1.17.0 flake8==7.3.0 pyside6==6.9.1 schedule==1.2.2 requests==2.32.4 types-requests==2.31.0.4

      - name: Run black (format check)
        run: black --check .

      - name: Run mypy (type check)
        run: mypy .

      - name: Run flake8 (lint check, non-blocking)
        continue-on-error: true
        run: flake8 .