name: CI

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  security-events: write

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy flake8

    - name: Run black (format check)
      run: black --check .

    - name: Run mypy (type check)
      run: mypy .

    - name: Run flake8 (lint check, non-blocking)
      continue-on-error: true
      run: flake8 .